name: Java CI

on:
  push:
    branches: ["main", "development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install jacoco:report

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sourcecodeanalyzer
          path: sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar

  after_success:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: sourcecodeanalyzer
          path: sourcecodeanalyzer/target/

      - name: Run sourcecodeanalyzer
        run: java -jar ./sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar sourcecodeanalyzer/src/test/resources/TestClass.java regex local metrics_results csv

      - name: CI Test
        run: diff metrics_results.csv sourcecodeanalyzer/src/test/resources/correct_output.csv